### ISSUE TITLE
adam error

### ISSUE THREAD

**Issue by tane64** [bouwew/adam#1]
Log Details (ERROR)
adam: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adam/climate.py", line 234, in update
    self._api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/adam/__init__.py", line 102, in update
    data = self.api.get_device_data(data_id, device['ctrl_id'])
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 122, in get_device_data
    presets = self.get_presets_from_id(domain_objects, key)
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 294, in get_presets_from_id
    "zone_setpoint_and_state_based_on_preset",
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 345, in get_rule_id_and_zone_location_by_template_tag
    schema_ids[rule_id] = location_id
UnboundLocalError: local variable 'location_id' referenced before assignment

**Comment by bouwew** [comment]
Thanks for letting me know.

Please update the version number in manifest.json to 0.0.10, then restart HA and let me know if the error is gone.

**Comment by bouwew** [comment]
Please use version 0.0.11.

**Comment by bouwew** [comment]
Please use 0.0.14.

**Comment by tane64** [comment]
After update / restart.

adam: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adam/climate.py", line 234, in update
    self._api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/adam/__init__.py", line 102, in update
    data = self.api.get_device_data(data_id, device['ctrl_id'])
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 122, in get_device_data
    presets = self.get_presets_from_id(domain_objects, key)
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 294, in get_presets_from_id
    "zone_setpoint_and_state_based_on_preset",
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 345, in get_rule_id_and_zone_location_by_template_tag
    schema_ids[rule_id] = location_id
UnboundLocalError: local variable 'location_id' referenced before assignment

**Comment by bouwew** [comment]
Just to be sure, which version did you use? 0.014?

**Comment by tane64** [comment]
Just downloaded.. Looks version 0.0.9 not the .14

**Comment by bouwew** [comment]
Did you follow the instruction: edit manifest.json on your system and change the version number from 0.0.9 to 0.0.14?

**Comment by bouwew** [comment]
That's all you need to do. No other changes.

**Comment by tane64** [comment]
Okay thank you. Done that. Same result..will test 2 hours.
====
Log Details (ERROR)
Sun Feb 09 2020 10:10:39 GMT+0100 (Midden-Europese standaardtijd)
adam: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adam/climate.py", line 234, in update
    self._api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/adam/__init__.py", line 102, in update
    data = self.api.get_device_data(data_id, device['ctrl_id'])
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 124, in get_device_data
    presets = self.get_presets_from_id(domain_objects, key)
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 297, in get_presets_from_id
    "zone_setpoint_and_state_based_on_preset",
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 349, in get_rule_id_and_zone_location_by_template_tag
    schema_ids[rule_id] = location_id
UnboundLocalError: local variable 'location_id' referenced before assignment

**Comment by bouwew** [comment]
Please write version number 0.0.15 into manifest,json, I just found that 0.0.14 doesn't work.
No need to test for hours, if there is an error, it does not work :)

**Comment by bouwew** [comment]
For my info, what kind of thermostats are in your system?
And what kind of your heating device do you use?

I guess you do not use a weekschedule for one of your thermostats? The error is related to such a schedule not being there. Can you please confirm that you do not use a weekschedule?

**Comment by tane64** [comment]
Done: 15

Adam: 3.0.10
Floor, Tom, Plugs, Lisa including week schedules..

Log Details (ERROR)
Sun Feb 09 2020 10:10:39 GMT+0100 (Midden-Europese standaardtijd)
adam: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/adam/climate.py", line 234, in update
    self._api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/adam/__init__.py", line 102, in update
    data = self.api.get_device_data(data_id, device['ctrl_id'])
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 124, in get_device_data
    presets = self.get_presets_from_id(domain_objects, key)
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 297, in get_presets_from_id
    "zone_setpoint_and_state_based_on_preset",
  File "/usr/local/lib/python3.7/site-packages/plugwise/plugwise.py", line 349, in get_rule_id_and_zone_location_by_template_tag
    schema_ids[rule_id] = location_id
UnboundLocalError: local variable 'location_id' referenced before assignment

**Comment by bouwew** [comment]
Please change to version 0.0.16

**Comment by tane64** [comment]
Done . Same result.

**Comment by bouwew** [comment]
Hmm, this is a head scratcher...

**Comment by bouwew** [comment]
Just to be sure, you are restarting HA after changing the version number in manifest.json?

**Comment by bouwew** [comment]
And HA is really restarting? And not restarting but throwing an error in the log?

**Comment by bouwew** [comment]
Can you please share the XML-data from /core/domain_objects?
Most likely there's a change in de format or contents in the new firmware, just like there is in the presets I just learned from Riemers.

**Comment by tane64** [comment]
Send via mail.

**Comment by bouwew** [comment]
Now I see a new error, that helps :)

**Comment by bouwew** [comment]
I found the culprit:

One line shows this: `<template id="99e6c1690d4041b0bf7881d9b9d65257" tag="zone_setpoint_and_state_based_on_preset">'
The others show this: <template id="99e6c1690d4041b0bf7881d9b9d65257" tag="zone_setpoint_and_state_based_on_preset"/>

There is a / missing in the one line. Plugwise to fix I think :)

**Comment by tane64** [comment]
Okay. Thanks will report that. En quick fix?

**Comment by bouwew** [comment]
I will take a break now, I have been programming for too long already :)

**Comment by tane64** [comment]
Have a nice day. Thanks
